# Configuración general
project_name: "bank_marketing_ml"
random_seed: 42

# Rutas
data:
  raw_path: "data/raw/bank-additional-full.csv"
  separator: ";"
  target_column: "y"
  task_type: "classification"  # 'classification' o 'regression'
  
# Validación del esquema
schema:
  expected_columns:
    - age
    - job
    - marital
    - education
    - default
    - housing
    - loan
    - contact
    - month
    - day_of_week
    - duration
    - campaign
    - pdays
    - previous
    - poutcome
    - emp.var.rate
    - cons.price.idx
    - cons.conf.idx
    - euribor3m
    - nr.employed
    - y
  max_null_percentage: 0.05  # 5% máximo de nulos permitidos

# División de datos
split:
  test_size: 0.2
  stratify: true
  shuffle: true

# Preprocesamiento
preprocessing:
  numeric_features:
    - age
    - duration
    - campaign
    - pdays
    - previous
    - emp.var.rate
    - cons.price.idx
    - cons.conf.idx
    - euribor3m
    - nr.employed
  
  categorical_features:
    - job
    - marital
    - education
    - default
    - housing
    - loan
    - contact
    - month
    - day_of_week
    - poutcome
  
  imputation:
    numeric_strategy: "median"
    categorical_strategy: "most_frequent"
  
  scaling:
    method: "standard"  # 'standard' o 'minmax'
  
  pca:
    enabled: false
    variance_ratio: 0.95

# Validación cruzada
cross_validation:
  n_splits: 5
  shuffle: true

# Métricas
metrics:
  classification:
    primary: "roc_auc"
    secondary:
      - "average_precision"
      - "balanced_accuracy"
      - "f1"
  
  regression:
    primary: "neg_root_mean_squared_error"
    secondary:
      - "r2"

# Modelos supervisados
supervised_models:
  baseline:
    model_type: "logistic_regression"
    params:
      max_iter: 1000
      class_weight: "balanced"
  
  random_forest:
    model_type: "random_forest"
    class_weight: "balanced"
    
    # Tuning etapa 1: RandomizedSearch
    randomized_search:
      n_iter: 20
      params:
        n_estimators: [50, 100, 200, 300, 500]
        max_depth: [5, 10, 15, 20, 25, null]
        max_features: ["sqrt", "log2", 0.3, 0.5]
        min_samples_split: [2, 5, 10, 20]
        min_samples_leaf: [1, 2, 4, 8]
    
    # Tuning etapa 2: GridSearch
    grid_search:
      enabled: true
      # Se generará dinámicamente alrededor del mejor modelo

# K-means clustering
kmeans:
  k_range: [2, 3, 4, 5, 6, 7, 8, 9, 10]
  n_init: 10
  max_iter: 300
  metrics:
    - "inertia"
    - "silhouette"
    - "calinski_harabasz"
    - "davies_bouldin"

# Salidas
output:
  base_dir: "outputs"
  models_dir: "outputs/models"
  reports_dir: "outputs/reports"
  figures_dir: "outputs/figures"
  logs_dir: "outputs/logs"